version: "3.8"

services:
  # Frontend Service
  frontend:
    build:
      context: .  # Path to your frontend code
      dockerfile: Dockerfile.frontend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/deploify_db
    networks:
      - app-network
    depends_on:
      - postgres

  # Worker Service
  worker:
    build:
      context: .  # Path to your worker code
      dockerfile: Dockerfile.frontend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/deploify_db
    networks:
      - app-network
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:13  # Use PostgreSQL image (can adjust version)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deploify_db  # Your default database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for the database
    networks:
      - app-network
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
