FROM node:18-alpine AS Builder 

WORKDIR /app

RUN cd apps/worker

COPY . .

RUN npm ci

RUN npm lint

RUN npm run build

FROM oven/bun:latest AS Runner

WORKDIR /app

COPY --from=Builder .

RUN bun dist/index.js